var quotes = [
	["Art is art. Everything else is everything else.", "<a href=\"http://en.wikipedia.org/wiki/Ad_Reinhardt\">AD REINHARDT</a>"],
	["It's easy to get bogged down in the circumstantial and mundane, but if we connect to our passion, that in itself will be regenerative; we won't have to wait for the energy, it will be there. But how do we connect to that passion? One of my favorite phrases, which a friend taught me, is that we need to pay &quot;exquisite attention&quot; to our responses to things -- noticing what makes our flame glow brighter. If we pay attention to those things, we'll be able to catch the flame and feed it.", "<a href=\"http://www.utne.com/Environment/Utne-Reader-Visionary-Nina-Simons-Conscientious-PR.aspx\">NINA SIMONS</a>, President, Collective Heritage Institute"],
	["Mass production strips every image of its singularity, rendering it schematic and quickly identifiable, so that it resembles a sign.  A sign is a command.  Its message comes all at once. It means one thing only--nuance and ambiguity are not important properties of signs--and is no better for being hand-made.  Works of art speak in a more complicated way of relationships, hints, uncertainties, and contradictions.  They do not force meanings on their audience; meaning emerges, adds up, unfolds from their imagined centres.  A sign dictates meaning, a work of art takes one through the process of discovering meaning.  In short, paintings educate but signs discipline; mass language always tends to speak in the imperative voice.", "<a href=\"http://en.wikipedia.org/wiki/Robert_Hughes_(critic)\">ROBERT HUGHES</a> in The Shock of the New."],
	["Success supposes endeavor.", "<a href=\"http://en.wikipedia.org/wiki/Jane_austen\">JANE AUSTEN</a>"],
	["Success breeds confidence.", "<a href=\"http://en.wikipedia.org/wiki/Beryl_Markham\">BERYL MARKHAM</a>"],
	["Success is a great healer.", "GRACE ATHERTON"],
	["Sanity is perhaps the ability to punctuate.", "<a href=\"http://www.independent.co.uk/news/obituaries/idris-parry-scholar-of-german-literature-800545.html\">PARRY IDRIS</a>"],
	["Sanity is only that which is within the frame of reference of conventional thought.", "<a href=\"http://en.wikipedia.org/wiki/Eric_fromm\">ERIC FROMM</a>"],
	["Each one of us, in his timidity, has a limit beyond which he is outraged. It is inevitable that he who by concentrated application has extended this limit for himself, should arouse the resentment of those who have accepted conventions which, since accepted by all, require no initiative of application. And this resentment generally takes the form of meaningless laughter or of criticism, if not persecution. But this apparent violation is preferable to the monstrous habits condoned by etiquette and estheticism.", "<a href=\"http://en.wikipedia.org/wiki/Man_Ray\">MAN RAY</a>"],
	["Business Art is the step that comes after Art.", "<a href=\"http://en.wikipedia.org/wiki/Andy_warhol\">ANDY WARHOL</a>"],
	["...be absolute moderne.", "<a href=\"http://en.wikipedia.org/wiki/Rimbaud\">RIMBAUD</a>"],
	["With the most primitive means the artist creates something which the most ingenious and efficient technology will never be able to create.", "<a href=\"http://en.wikipedia.org/wiki/Kasimir_Malevich\">KASIMIR MALEVICH</a>"],
	["I've found that every time I've made a radical change, it's helped me feel buoyant as an artist.", "<a href=\"http://en.wikipedia.org/wiki/David_bowie\">DAVID BOWIE</a>"],
	["God made everything out of nothing.  But the nothingness shows through.", "<a href=\"http://en.wikipedia.org/wiki/Paul_Valery\">PAUL VALERY</a>"],
	["I produce music as an apple tree produces apples.", "<a href=\"http://en.wikipedia.org/wiki/Camille_Saint-Saens\">CAMILLE SAINT-SAENS</a>"],
	["The triumph of anything is a matter of organization.", "<a href=\"http://en.wikipedia.org/wiki/Kurt_Vonnegut\">KURT VONNEGUT</a>"],
	["The nature of the work is to prepare for a good accident.", "<a href=\"http://en.wikipedia.org/wiki/Sidney_Lumet\">SIDNEY LUMET</a>"],
	["The artist need not know very much; best of all let him work instinctively and paint as naturally as he breathes or walks.", "<a href=\"http://en.wikipedia.org/wiki/Emil_Nolde\">EMIL NOLDE</a>"],
	["We work not only to produce but to give value to time.", "<a href=\"http://en.wikipedia.org/wiki/Eugene_Delacroix\">EUGENE DELACROIX</a>"],
	["What is real is not the external form, but the essence of things . . . it is impossible for anyone to express anything essentially real by imitating its exterior surface.", "<a href=\"http://en.wikipedia.org/wiki/Brancusi\">BRANCUSI</a>"],
	["...I knew that a day I took away from the work did not make me too happy.  I just feel that I'm in tune with the right vibrations in the universe when I'm in the process of working.  I always felt right when I was right here.  And even if I didn't want to compose, so I painted or stacked the pieces or something.  In my studio I'm as happy as a cow in her stall.  That's the only place where everything is all right.", "<a href=\"http://en.wikipedia.org/wiki/Louise_Nevelson\">LOUISE NEVELSON</a>"],
	["Once, after finishing a picture, I thought I would stop for awhile, take a trip, do things--the next time I thought of this, I found five years had gone by.", "<a href=\"http://en.wikipedia.org/wiki/Willem_De_Kooning\">WILLEM DE KOONING</a>"],
	["Gertrude Stein wrote to Thornton Wilder in September 1936 from Bilignin, France:<br />My dear Thornton, I just read in this morning's paper that [P.G.] Wodehouse says that they give him $104,000 for doing nothing at Hollywood they keep him there but they do not use what they ask him to do, now that would just suit us fine, we want a payed [vacation] which is a la mode here now, and of course we are not valuable like he is, but for considerable less would we write dialogue and titles that they do not want to use, not at all do we insist that they use our works printed or unprinted not at all, we just want to run around and do nothing and be payed largely for it, that is as everything they do not want, it is a pleasant xtravagence and we are just pining for pleasant xtravagence, so keep your eyes and ears open, if they want us we will come, we would love to be payed largely and we are kind of tired of just staying here beside it is coming too high to live in Europe like that, we are nutting in the woods and then Alice makes cakes of the nuts, which is a pleasant life too, but a vacance paye and it might be with you dear Thornton and lots of love.", "<a href=\"http://en.wikipedia.org/wiki/Gertrude_Stein\">GERTRUDE STEIN</a>"],
	["It is important to attend some obscure artistic exhibition or event where the artist is so distant, the creator/performer so arcane, that even having three Ph.D.s will not help you understand it any better.  The main reason to go is so that you will be able to use vocabulary that you have been hearing and reading but don't quite understand.  You will be able to use academic words or hip art-words like &quot;juxtapose,&quot; &quot;contextualize,&quot; &quot;appropriate&quot; and &quot;deconstructionist&quot; when commenting on art.  Make sure to let everyone know that you have attended such an event, and even if you didn't understand it, never say that it was &quot;interesting&quot; or &quot;neat.&quot;  Say either, &quot;I understand it historically&quot; or &quot;I can appreciate its minimalness.&quot;  REMEMBER:  Attending an obscure, out-of-the-way cultural experience qualifies one for the title of trendsetter.", "<a href=\"http://en.wikipedia.org/wiki/Karen_Finley\">KAREN FINLEY</a> from Enough is Enough."],
	["As music is the poetry of sound, so is painting the poetry of sight and the subject-matter has nothing to do with harmony of sound or of color.  The great musicians knew this.  Beethoven and the rest wrote music - simply music; symphony in this key, concerto or sonata in that...", "<a href=\"http://en.wikipedia.org/wiki/James_Mcneill_Whistler\">JAMES McNEILL WHISTLER</a>"],
	["The work of the master reeks not of the sweat of the brow - suggests no effort - and is finished from its beginning.", "<a href=\"http://en.wikipedia.org/wiki/James_Mcneill_Whistler\">JAMES McNEILL WHISTLER</a>"],
	["Elegance is reduction, simplification, condensation.  It is spare, stark, sleek.  Elegance is cultivated abstraction.  The source of Greek and Roman classicism - clarity, order, proportion, balance - is in Egypt.", "<a href=\"http://en.wikipedia.org/wiki/Camille_paglia\">CAMILLE PAGLIA</a>"],
	["This life is a hospital where every patient is possessed with the desire to change beds...", "<a href=\"http://en.wikipedia.org/wiki/Charles_Baudelaire\">CHARLES BAUDELAIRE</a>"],
	["Whistler's encounters with Oscar Wilde have passed into history.  He and Wilde were the two most conspicuous figures in the social London of the Eighties.  They were often compared as wits but there was no comparison.  Oscar was witty but his wit seems more labored, more carefully worked out and he could borrow and adapt from others when at a loss.  That is the explanation of the often-told story:  Oscar's, &quot;I wish I had said that, Whistler&quot;, and Whistler's &quot;You will, Oscar, you will.&quot;", "<a href=\"http://en.wikipedia.org/wiki/Elizabeth_Robins_Pennell\">PENNELL</a> from <span class=\"italic\">The Art of Whistler</span>."],
	["During his trial when he was suing Ruskin for publicly saying one of his Nocturne paintings was not worth the price he asked for it:<br /><br />Whistler:  Let us say then, how long did I take to 'knock off'--I think that is it--to knock off that Nocturne; well, as well as I remember, about a day . . . I may have still put a few more touches to it the next day if the painting were not dry.  I had better say, then, that I was two days at work on it.<br /><br />Attorney-General:  The labor of two days then, is that for which you ask two hundred guineas?<br /><br />Whistler:  No, I ask it for the knowledge of a lifetime<br /><br />&quot;Over and over again did the Attorney-General cry out aloud, in the agony of his cause, 'what is to become of painting if the critics withhold their lash?&quot;<br /><br />&quot;As well might he ask what is to become of mathematics under similar circumstances, were they possible.  I maintain that two and two the mathematician would continue to make four, in spite of the whine of the amateur for three, or the cry of the critic for five.  . . . The Observatory at Greenwich under the direction of an Apothecary!  The College of Physicians with Tennyson as President!  and we know that madness is about.  But a school of art with an accomplished litterateur at its head disturbs no one!&quot;", "<a href=\"http://en.wikipedia.org/wiki/James_Mcneill_Whistler\">JAMES McNEILL WHISTLER</a> from <span class=\"italic\">The Art of Whistler</span> by <a href=\"http://en.wikipedia.org/wiki/Elizabeth_Robins_Pennell\">Elizabeth Robins Pennell</a>"],
	["From Great Consciousness vision Harlem 1948 buildings standing in Eternity<br />I realized entire Universe was manifestation of One Mind - <br />My teacher was William Blake - my life work Poesy,<br />transmitting that spontaneous awareness to Mankind.", "<a href=\"http://en.wikipedia.org/wiki/Allen_Ginsberg\">ALLEN GINSBERG</a> from <span class=\"italic\">Who</span>"],
	["Which country is real, mine or the teacher's? My wish is that we might progressively lose our confidence in what we think we believe and the things we consider stable and secure, in order to remind ourselves of the infinite number of things still waiting to be discovered.", "<a href=\"http://en.wikipedia.org/wiki/Antoni_Tapies\">ANTONI TAPIES</a>"],
	["When my daughter was about seven years old, she asked me one day what I did at work.  I told her I worked at the college - that my job was to teach people how to draw.<br /><br />She stared back at me, incredulous, and said, &quot;You mean they forget?&quot;", "<a href=\"http://ikemotoart.com/about.php\">HOWARD IKEMOTO</a>"],
	["The People adore authority.", "<a href=\"http://en.wikipedia.org/wiki/Charles_Baudelaire\">CHARLES BAUDELAIRE</a>"],
	["That which is not slightly distorted lacks sensible appeal; from which it follows that irregularity - that is to say, the unexpected, surprise and astonishment, are an essential part and characteristic of beauty.", "<a href=\"http://en.wikipedia.org/wiki/Charles_Baudelaire\">CHARLES BAUDELAIRE</a>"],
	["I have nothing to say and I'm saying it.", "<a href=\"http://en.wikipedia.org/wiki/John_cage\">JOHN CAGE</a>"],
	["Only when he no longer knows what he is doing does the painter do good things.", "<a href=\"http://en.wikipedia.org/wiki/Edgar_Degas\">EDGAR DEGAS</a>"],
	["Skin has become inadequate in interfacing with reality.  Technology has become the body's new membrane of existence.", "<a href=\"http://en.wikipedia.org/wiki/Nam_June_Paik\">NAM JUNE PAIK</a>"],
	["Art enables us to find ourselves and lose ourselves at the same time.", "<a href=\"http://en.wikipedia.org/wiki/Thomas_Merton\">THOMAS MERTON</a>"],
	["There are so many dreams beyond your night, and so much sunshine beyond your grey walls. But you can't see it because you stay at home. There is so much sky above your roof. Is your door so old that it won't open, or are you staying at home because you're afraid of catching a chill.", "<a href=\"http://en.wikipedia.org/wiki/Francoise_Hardy\">FRANCOISE HARDY</a>"],
	["Art is the appearance of the idea.", "<span class=\"author\">HEGEL-SCHILLER</span>"],
	["I assume the senses crave sources of maximum information, that the eye benefits by exercise, stretch, and expansion towards materials of complexity and substance, . . . conditions which alert the total sensibility - cast it almost in stress - extend insight and response, the basic responsive range of empathetic-kinesthetic vitality.", "<a href=\"http://en.wikipedia.org/wiki/Carolee_Schneemann\">CAROLEE SCHNEEMANN</a>"],
	["And then you sock in the darks.", "<a href=\"http://www.malcolmmyers.com/\">MALCOLM MYERS</a>, Watercolor Instructor"],
	["Space is all one space and thought is all one thought, but my mind divides its spaces into spaces into spaces and thoughts into thoughts into thoughts.  Like a large condominium.  Occasionally I think about the one Space and the one Thought, but usually I don't.  Usually I think about my condominium.", "<a href=\"http://en.wikipedia.org/wiki/Andy_warhol\">ANDY WARHOL</a>"],
	["All Pictures that's Painted with Sense &amp; with Thought Are Painted by Madmen as sure as a Groat;  For the Greater the Fool in the Pencil more blest,  And when they are drunk they always paint best.", "<a href=\"http://en.wikipedia.org/wiki/William_blake\">WILLIAM BLAKE</a>"],
	["To know what you prefer instead of humbly saying Amen to what the world tells you you ought to prefer, is to have kept your soul alive.", "<a href=\"http://en.wikipedia.org/wiki/Robert_Louis_Stevenson\">ROBERT LOUIS STEVENSON</a>"],
	["It has bothered me all my life that I do not paint like everybody else.", "<a href=\"http://en.wikipedia.org/wiki/Henri_Matisse\">HENRI MATISSE</a>"],
	["I have taken up some things which it is impossible to do:  clear water with grass waving at the bottom.  It is wonderful to look at, but to try to paint it is enough to make one insane.", "<a href=\"http://en.wikipedia.org/wiki/Claude_monet\">CLAUDE MONET</a>"],
	["With the void, full powers.", "<a href=\"http://en.wikipedia.org/wiki/Albert_Camus\">ALBERT CAMUS</a>"],
	["The Void took place on 28 April 1958, at the Galerie Iris Clert in Paris.  It represented an attempt to conquer uncharted territory, to capture absolute blue in empty space.-&quot;the far side of the sky.&quot;  A highly visible accompanying symbol was planned, a &quot;blue project&quot; in which an obelisk in Place de la Concorde was to be illuminated by blue floodlights.  However the prefect of police withdrew his permission at the last moment.  The evening of the exhibition, the windows of the exhibition space shone in the inimitable International Klein Blue.  Posted next to the entrance under a huge blue canopy were two Republican guards in full dress uniform, gatekeepers symbolizing a rite of passage into an unknown dimension.  Klein had removed all the furniture from the small 150-square-foot gallery room.  He spent 48 hours painting the room white, using the same medium he used for his monochrome canvases, in order to retain the luminosity and intrinsic value of this non-color.<br /><br />Perhaps it was the eccentric, not to say crazy nature of the event that led it to be eagerly awaited on the Paris scene.  At any rate, it attracted over 3,000 people.  They were offered a blue cocktail prepared specially for the show (and later reported with chagrin that it had dyed certain bodily fluids bright blue).  Two &quot;immaterial&quot; works were actually sold.  Albert Camus reacted with a poetic entry in the visitors' album, &quot;With the void, full powers.&quot;", "paraphrased and quoted from <a href=\"http://en.wikipedia.org/wiki/Yves_Klein\">YVES KLEIN</a>, 1928-1962, International Klein Blue, by <a href=\"http://de.wikipedia.org/wiki/Hannah_Weitemeier\">HANNA WEITEMEIER [link is in German]</a>"],
	["The visible is how we orient ourselves.  It remains our principal source of information about the world.  Painting reminds us of what is absent.  What we don't see anymore.", "<a href=\"http://en.wikipedia.org/wiki/Squeak_carnwath\">SQUEAK CARNWATH</a>"],
	["We learn to do something by doing it.  There is no other way.", "<a href=\"http://en.wikipedia.org/wiki/John_Holt_(educator)\">JOHN HOLT, Educator</a>"],
	["Music is your own experience, your thoughts, your wisdom.  If you don't live it, it won't come out your horn.", "<a href=\"http://en.wikipedia.org/wiki/Charlie_parker\">CHARLIE PARKER</a>"],
	["Yves Klein took out a patent on the color he invented, IKB, or International Klein Blue--he mixed pure pigment with a synthetic resin normally applied as a fixative--the result was that the pigments were bound without materially altering their vibrant luminosity.", "<a href=\"http://de.wikipedia.org/wiki/Hannah_Weitemeier\">HANNA WEITEMEIER [link is in German]</a>, <span class=\"italic\">Yves Klein</span>, the book."],
	["I don't feel like I get germs when I hold money.  Money has a certain kind of amnesty.  I feel, when I'm holding money, that the dollar bill has no more germs on it than my hands do.  When I pass my hand over money, it becomes perfectly clean to me.  I don't know where it's been - who's touched it and with what - but that's all erased the moment I touch it.", "<a href=\"http://en.wikipedia.org/wiki/Andy_warhol\">ANDY WARHOL</a>"],
	["There is no rewind button on the BETAMAX of life.", "<a href=\"http://en.wikipedia.org/wiki/Nam_June_Paik\">NAM JUNE PAIK</a>"],
	["The madman need no longer wander the corridors of the asylum.  We cruise the interstates.", "<a href=\"http://www.peterhalley.com/\">PETER HALLEY</a>"],
	["Even beauties can be unattractive.  If you catch a beauty in the wrong light at the right time, forget it.  I believe in low lights and trick mirrors.  I believe in plastic surgery.", "<a href=\"http://en.wikipedia.org/wiki/Andy_warhol\">ANDY WARHOL</a>"],
	["Violet has the shortest wavelength of the spectrum.  Behind it, the invisible ultraviolet.  Roses are Red, Violets are Blue.  Poor violet violated for a rhyme.", "<a href=\"http://en.wikipedia.org/wiki/Derek_Jarman\">DEREK JARMAN</a>, Chroma"],
	["Red protects itself.  No color is as territorial.  It stakes a claim, is on the alert against the spectrum.", "<a href=\"http://en.wikipedia.org/wiki/Derek_Jarman\">DEREK JARMAN</a>, Chroma"],
	["To feel the soul without explaining it, without vocabulary, and to represent this sensation.", "<a href=\"http://en.wikipedia.org/wiki/Yves_Klein\">YVES KLEIN</a>"],
	["We began as mineral.  We emerged into plant life, and into the animal state, and then into being human, and always we have forgotten our former states, except in early spring when we slightly recall being green again.", "<a href=\"http://en.wikipedia.org/wiki/Rumi\">RUMI</a> (1207 - 1237 AD)"],
	["Indian yellow, banned.  Cows were poisoned with mango leaves and the colour was made from their urine.  it is the bright yellow in Indian miniatures.  Although yellow occupies one-twentieth of the spectrum, it is the brightest color.", "<a href=\"http://en.wikipedia.org/wiki/Derek_Jarman\">DEREK JARMAN</a>, Chroma"],
	["Life shrinks or expands in proportion to one's courage.", "<a href=\"http://en.wikipedia.org/wiki/Anais_Nin\">ANAIS NIN</a>"],
	["Sell your cleverness and buy bewilderment.", "<a href=\"http://en.wikipedia.org/wiki/Rumi\">JALAL UD-DIN RUMI</a>"],
	["Nobody objects to a woman being a good writer or sculptor or geneticist if at the same time she manages to be a good wife, good mother, good-looking, good tempered, well-groomed, and unaggressive.", "<span class=\"author\">LESLIE M. McINTYRE</span>"],
	["A certain blue enters your soul.  A certain red has an effect on your blood-pressure.", "<a href=\"http://en.wikipedia.org/wiki/Henri_Matisse\">HENRI MATISSE</a>"],
	["I think that probably the most potent desire for a painter, an image-maker, is to see it.  To see what the mind can think and imagine, to realize it for oneself, through oneself, as concretely as possible.", "<a href=\"http://en.wikipedia.org/wiki/Philip_Guston\">PHILIP GUSTON</a>"],
	["Art is beautiful but it is hard, like a religion without a purpose.", "<a href=\"http://en.wikipedia.org/wiki/Gunter_Brus\">GUNTER BRUS</a>"],
	["...when we rounded into the lowest semi-circular gallery, I saw my first Barnett Newman, a universe of blue paint by which I was immediately ravished.  My whole self lifted into it.  &quot;Enough&quot; was my radiant feeling-for once in my life enough space, enough color.  It seemed to me that I had never before been free.  Even running in a field had not given me the same airy beatitude.  I would not have believed it possible had I not seen it with my own eyes.  Such openness wiped out with one swoop all my puny ideas.  I staggered out into the street intoxicated with freedom, lifted into a realm I had not dreamed could be caught into existence.  I was completely taken by surprise, the more so as I had only earlier that day been thinking how I felt like a plowed field, my children all born, my life laid out; I saw myself stretched like brown earth in furrows, open to the sky, well planted, my life as a human being complete.  My yearning for a family, my husband and my children, had been satisfied.  I had looked for no more in the human sense and had felt content.", "<a href=\"http://en.wikipedia.org/wiki/Anne_Truitt\">ANNE TRUITT</a>"],
	["Art is everywhere, except it has to pass through a creative mind.", "<a href=\"http://en.wikipedia.org/wiki/Louise_Nevelson\">LOUISE NEVELSON</a>"],
	["Artists are the people among us who realize creation didn't stop on the sixth day.", "<a href=\"http://en.wikipedia.org/wiki/Joel_peter_witkin\">JOEL PETER WITKIN</a>"],
	["I do not literally paint that table, but the emotion it produces upon me.", "<a href=\"http://en.wikipedia.org/wiki/Henri_Matisse\">HENRI MATISSE</a>"],
	["I love California; everything is so artificial.", "<a href=\"http://en.wikipedia.org/wiki/David_Hockney\">DAVID HOCKNEY</a>"],
	["To be a painter now is to be part of a very small, endangered species.", "<a href=\"http://en.wikipedia.org/wiki/Howard_Hodgkin\">HOWARD HODGKIN</a>"],
	["Forget safety. Live where you fear to live. Destroy your reputation. Be notorious.", "<a href=\"http://en.wikipedia.org/wiki/Rumi\">RUMI</a>"],
	["Let the beauty we love be what we do.", "<a href=\"http://en.wikipedia.org/wiki/Rumi\">RUMI</a>"],
	["I put in my pictures everything I like.  So much the worse for the things - they have to get along with one another.", "<a href=\"http://en.wikipedia.org/wiki/PICASSO\">PICASSO</a>"],
	["Two Basic systems:  Development and Maintenance.  The sourball of every revolution:  after the revolution, who's going to pick up the garbage on Monday morning?...<br /><br />...Maintenance is a drag; it takes all the fucking time (lit.)  The mind boggles and chafes at the boredom.  The culture confers lousy status on maintenance jobs--minimum wages, housewives - no pay. Clean your desk, wash the dishes, clean the floor, wash your clothes, wash your toes, change the baby's diaper, finish the report, correct the typos, mend the fence, keep the customer happy, throw out the stinking garbage, watch out don't put things in your nose, what shall I wear, I have no sox, pay your bills, don't litter, save string, wash your hair, change the sheets, go to the store, I'm out of perfume, say it again - he doesn't understand, seal it again - it leaks, go to work, this art is dusty, clear the table, call him again, flush the toilet, stay young.", "<a href=\"http://en.wikipedia.org/wiki/Mierle_Laderman_Ukeles\">MIERLE LADERMAN UKELES</a> Maintenance Art Manifesto (1969)"],
	["The Will of the statue.<br />&quot;I want to be alone at all costs,&quot; said the statue with the eternal view.  Wind, wind refreshed my burning cheaks.  And the battle began, terrible.<br />The shattered skulls fell and the brains bulged from it, polished as if it was ivory.<br />Flee, flee towards the plain and radiant city.<br />Behind, the demons wipped me with all might.  My calfs were bleeding awfully.  Oh sadness of the lonely statue down there.  Bliss. And never the sun.  Never the yellow comforter of the enlightened earth.<br />It wants.<br />Silence.<br />It loves its strange soul.  It is conquered.<br />And now the sun stopped all above in the middle of the skies; and the statue in its happiness of eternity lost its soul in the contemplation of its shadow.<br />There is a room, which shutters are always closed.  In a corner a book that nobody has read.  At a wall a painting that one cannot look at without crying.", "<a href=\"http://en.wikipedia.org/wiki/George_de_Chirico\">GEORGE DE CHIRICO</a>, 1912-1913 (reproduced to reflect the spelling given in the original)"],
	["Life proceeds amid an incessant network of signals.", "<a href=\"http://en.wikipedia.org/wiki/George_Steiner\">GEORGE STEINER </a>"],
	["It don't mean a thing if it ain't got that swing.", "<a href=\"http://en.wikipedia.org/wiki/Duke_ellington\">DUKE ELLINGTON</a>"],
	["The true mystery of the world is the visible, not the invisible.", "<a href=\"http://en.wikipedia.org/wiki/Oscar_wilde\">OSCAR WILDE</a>"],
	["Most artists are doing basically the same thing--staying off the streets.", "<a href=\"http://en.wikipedia.org/wiki/Edward_Ruscha\">EDWARD RUSCHA</a>"],
	["Art comes from art:  I remember going to the Matisse show and seeing how Matisse had taken one of his own paintings, worked from it and transformed it, and that had led on to the next one and the next.", "<a href=\"http://en.wikipedia.org/wiki/Anthony_Caro\">ANTHONY CARO</a>"],
	["Lesson Six:  Build Yourself Wings.  Fly straight ahead.  Walk a straight line.  Visit.  Leave a special sign on the door.  Make a gift of words.  Mark your path with books.  With clothes.  With food.  Join two distant places.  Two rocks.  Two people.  Bridge a river.  Build a city of sand.  Raise up a mound.", "<a href=\"http://en.wikipedia.org/wiki/Milan_Knizak\">MILAN KNIZAK</a>"],
	["I have put my talent into writing, my genius I have saved for living.", "<a href=\"http://en.wikipedia.org/wiki/Oscar_wilde\">OSCAR WILDE</a>"],
	["I don't want to achieve immortality through my work.  I want to achieve it by not dying.", "<a href=\"http://en.wikipedia.org/wiki/Woody_allen\">WOODY ALLEN</a>"],
	["The greatest enemy of art is the absence of Limitation.", "<a href=\"http://en.wikipedia.org/wiki/Orson_Welles\">ORSON WELLES</a>"],
	["A ballerina's life can be glorious.  But it does not get any easier.  I don't think anyone must ever think about it getting easier.", "<a href=\"http://en.wikipedia.org/wiki/Alicia_Markova\">ALICA MARKOVA</a>"],
	["I can't teach you to be an artist; all I can do is help you learn to see.", "<span class=\"author\">J.P. LOVELESS</span>"],
	["We don't make these pictures to make money.  We make money so that we can make more pictures.", "<a href=\"http://en.wikipedia.org/wiki/Walt_Disney\">WALT DISNEY</a>"],
	["For these few days the hills are bright with cherry blossom.  Longer, and we should not prize them so.", "<a href=\"http://en.wikipedia.org/wiki/Yamabe_no_Akahito\">YAMABE NO AKAHITO</a>"],
	["How do people get rich?  I started out in life asking this question.  Whenever I saw a rich person I would ask where their money was from, and invariably, or should I say inevitably, the answer was a natural resource, or else an unnatural resource.  Oil would be a common answer, or real estate, or steel--this was before computers.  The answer was never the answer you wanted to hear.  The answer was never &quot;Poetry--their money's from poetry, Fran.&quot;  Or &quot;That's one of the great essay fortunes in this country.&quot; Or &quot;You know, he's the biggest epigram magnate in Europe.&quot; And so I learned that I was not in the moneymaking end of the money-making business.&quot;", "<a href=\"http://en.wikipedia.org/wiki/Fran_Lebowitz\">FRAN LEBOWITZ</a> on MONEY, from Vanity Fair July 1997."],
	["As for techniques and processes, as seen in the works themselves, neither public nor artists will find anything about them here.  Those things are learned in the studio and the public is interested only in the results.", "<a href=\"http://en.wikipedia.org/wiki/Charles_Baudelaire\">CHARLES BAUDELAIRE</a>, <span class=\"italic\">The Salon of 1846</span>"],
	["At times inactivity is preferable to mindless functioning.", "<a href=\"http://en.wikipedia.org/wiki/Jenny_Holzer\">JENNY HOLZER</a>"],
	["Creativity is a commodity that must be paid for.", "<a href=\"http://en.wikipedia.org/wiki/Stanley_Marcus\">STANLEY MARCUS</a>"],
	["An artist cannot speak about his art any more than a plant can discuss horticulture.", "<a href=\"http://en.wikipedia.org/wiki/Jean_Cocteau\">JEAN COCTEAU</a>"],
	["An artist is a creature driven by demons.  He doesn't know why they chose him and is usually too busy to wonder why.", "<a href=\"http://en.wikipedia.org/wiki/William_faulkner\">WILLIAM FAULKNER</a>"],
	["The night of which I speak is not to be confused with the night which Freud invited his patients to enter.  Freud was a modest housebreaker:  he absconded with a few mediocre pieces of furniture and some erotic photographs.  He never consecrated the abnormal as a transcendence; nor did he hail the great disorders.  He devised a confessional for bores.", "<a href=\"http://en.wikipedia.org/wiki/Jean_Cocteau\">JEAN COCTEAU</a>"],
	["I shall never forget what I saw at the Museum of Modern Art:  in a spotless schoolroom, fifty little girls painting away at tables covered with brushes, pots, tubes, bowls, staring into space and sticking out their tongues like the clever animals that ring a bell, tongues lolling and eyes vague.  Teachers supervise these young creators of abstract art and slap their wrists if what they paint represents something and dangerously inclines toward realism.  The mothers (still at the Picasso stage) are not admitted.", "<a href=\"http://en.wikipedia.org/wiki/Jean_Cocteau\">JEAN COCTEAU</a> (in New York)"],
	["It takes a very long time to become young.", "<a href=\"http://en.wikipedia.org/wiki/PICASSO\">PICASSO</a>"],
	["There are poets and grownups.", "<a href=\"http://en.wikipedia.org/wiki/Jean_Cocteau\">JEAN COCTEAU</a>"],
	["I want the kind of readers who remain children at any cost.  I can tell them at a glance:  loyalty to that first enchantment guards better than any cosmetic; than any diet, against the insults of age.  But alas for such readers, who would huddle safe and sound in the asylum of their credulous enchantment as if in the womb-our enervating century offends them by its chaos, its fidgets of light and space, the host of its excuses for dividing , for rending oneself from others and from oneself.", "<a href=\"http://en.wikipedia.org/wiki/Jean_Cocteau\">JEAN COCTEAU</a>"],
	["At Kobe, the first sight which catches my eye is a little girl playing hopscotch.  This five-year old chalks on the sidewalk the perfect circle with which Hokusai signed his letters.  Having completed this masterpiece, she hops off, sticking out her tongue.  I should like to take away that circle.  It yields up, at our first step, the secret of the Nipponese soul.  That calm like the solemn silence of the Meiji temple park, that laborious patience, that sureness of eye and hand, that clarity and cleanliness grant us either this miraculous woodwork or all the junk flooding the European market.", "<a href=\"http://en.wikipedia.org/wiki/Jean_Cocteau\">JEAN COCTEAU</a> (on a trip to Japan)"],
	["There is a case for saying that the creation of new aesthetic forms has been the most fundamentally productive of all forms of human activity.  Whoever creates new artistic conventions has found methods of interchange between people about matters which were incommunicable before.  The capacity to do this has been the basis of the whole of human history.", "<a href=\"http://en.wikipedia.org/wiki/John_Zachary_Young\">J. Z. YOUNG</a> (from the book, \"Art &amp; Physics\" by <a href=\"http://www.artandphysics.com/\">Leonard Schlain)</a>"],
	["The artist is the antenna of the race.", "<a href=\"http://en.wikipedia.org/wiki/Ezra_pound\">EZRA POUND</a> (from the book, \"Art &amp; Physics\" by <a href=\"http://www.artandphysics.com/\">Leonard Schlain)</a>"],
	["A new painting is a unique event, a birth, which enriches the universe as it is grasped by the human mind, by bringing a new form into it.", "<a href=\"http://en.wikipedia.org/wiki/Henri_Matisse\">HENRI MATISSE</a>"],
	["All the fun's in how you say a thing.", "<a href=\"http://en.wikipedia.org/wiki/Robert_Frost\">ROBERT FROST</a>"],
	["The man who has no inner life is a slave to his surroundings.", "<a href=\"http://en.wikipedia.org/wiki/Henri-Fr%C3%A9d%C3%A9ric_Amiel\">HENRI-FREDERIC AMEIL</a>"],
	["You have to trust your instincts.  There is a moment when an actor has it, and he knows it.", "<a href=\"http://en.wikipedia.org/wiki/Clint_Eastwood\">CLINT EASTWOOD</a>"],
	["As soon as there is life, there is danger.", "<a href=\"http://en.wikipedia.org/wiki/Ralph_Waldo_Emerson\">RALPH WALDO EMERSON</a>"],
	["From an interview with Donald Sultan by Julie L. Belcove:  &quot;A giant squash?&quot; the painter asks  referring to one of the (huge yellow and black) abstract still lifes hanging in his spacious TriBeCa studio.  &quot;It's not about being a giant squash.  It's about confronting color and material while also confronting the seeming permanence of objects.&quot;  To those who might say, &quot;I could paint that,&quot; Sultan responds, &quot;That's true.  I could fix a sink, but I don't.&quot;  &quot;Art is meant to cause these kinds of dialogs.  It's doing its job.  A dentist's job is not to cause pain-that's an artist's job.&quot;", "<a href=\"http://en.wikipedia.org/wiki/Donald_Sultan\">DONALD SULTAN</a>"],
	["That abominable and sensual act called reading the newspaper, thanks to which all the misfortunes and cataclysms in the universe over the last twenty-four hours, the battles which cost the lives of fifty-thousand men, the murders, the strikes, the bankruptcies, the fires, the poisonings, the suicides, the divorces, the cruel emotions of statesmen and actors, are transformed for us, who don't even care, into a morning treat, blending in wonderfully, in a particularly exciting and tonic way, with the recommended ingestion of a few sips of cafe au lait.", "<a href=\"http://en.wikipedia.org/wiki/Marcel_Proust\">MARCEL PROUST</a>"],
	["My little Renoirs.  Matisse describes having seen Renoir make these tiny canvases.  When he had finished working, he would use up the color left in his brushes on them.  It is true that the tourists collect the earth from his Cagnes garden and that the Americans would pay a lot for his paint rags.", "<a href=\"http://en.wikipedia.org/wiki/Jean_Cocteau\">JEAN COCTEAU</a> from <span class=\"italic\">The Cocteau Diaries, Volume One</span>"],
	["Continue reading Proust.  His magnificent intelligence is particularly fond of describing stupidity.  Which is ultimately exhausting.", "<a href=\"http://en.wikipedia.org/wiki/Jean_Cocteau\">JEAN COCTEAU</a> from <span class=\"italic\">The Cocteau Diaries, Volume One</span>"],
	["Keep braiding one's wavelengths back into oneself.  That way they gain all the more external power and surround us with a huge affective and protective zone.  Don't talk about this.  Never talk about our secret methods.  If we talk about them, they stop working.", "<a href=\"http://en.wikipedia.org/wiki/Jean_Cocteau\">JEAN COCTEAU</a> from <span class=\"italic\">The Cocteau Diaries, Volume One</span>"],
	["Our vanity, our passions, our spirit of imitation, our abstract intelligence, our habits have long been at work, and it is the task of art to undo this work of theirs, making us travel back in the direction from which we have come to the depths where what has really existed lies unknown within us.", "<a href=\"http://en.wikipedia.org/wiki/Marcel_Proust\">MARCEL PROUST</a>"],
	["Friendship is in the end no more than:  &quot;...a lie which seeks to make us believe that we are not irremediably alone.&quot;", "<a href=\"http://en.wikipedia.org/wiki/Marcel_Proust\">MARCEL PROUST</a>"],
	["The artist who gives up an hour of work for an hour of conversation with a friend knows that he is sacrificing a reality for something that does not exist (our friends being friends only in the light of an agreeable folly which travels with us through life and to which we readily accommodate ourselves, but which at the bottom of our hearts we know to be no more reasonable than the delusion of the man who talks to the furniture because he believes that it is alive).", "<a href=\"http://en.wikipedia.org/wiki/Marcel_Proust\">MARCEL PROUST</a>"],
	["Conversation, which is friendship's mode of expression, is a superficial digression which gives us nothing worth acquiring.  We may talk for a lifetime without doing more than indefinitely repeat the vacuity of a minute.", "<a href=\"http://en.wikipedia.org/wiki/Marcel_Proust\">MARCEL PROUST</a>"],
	["Through the last few decades it [the art object] has been ripped off the wall and twisted through every conceivable permutation, yet back to the wall it insists on going.", "<a href=\"http://en.wikipedia.org/wiki/Ashley_Bickerton\">ASHLEY BICKERTON</a>"],
	["One reads poetry with one's nerves.", "<a href=\"http://en.wikipedia.org/wiki/Wallace_Stevens\">WALLACE STEVENS</a>"],
	["The most astonishing quality of abstract painting is indeed its capacity to formulate what is still unknown or new--although everything refers to the canon of forms that exist in the world. The more beautiful and surprising a painting is, the more staggering are the associations it sets free. On the other hand, details from baroque or medieval Persian paintings can also evoke or be seen as abstraction. I believe in the richness and beauty of the human intellect and in its ability to understand the unknown and strange. I accordingly believe that there are more possibilities than simply plundering the archives of paintings and combining their elements, piling them on one another. Beauty through confusion; truth through collision!", "<a href=\"http://en.wikipedia.org/wiki/Daniel_Richter\">DANIEL RICHTER</a>, German abstract painter"],
	];

function random_num(num) {
	return (Math.floor(Math.random() * num));
}


// global image indices
var cur_index;
var next_index;
var new_index;
var ssid;


// init_quote()
// choose a random quote from the list and display it in a simple paragraph
function init_quote() {
	// initialize random indices into quotes array
	cur_index = random_num(quotes.length);
	next_index = random_num(quotes.length);
	// don't let quotes repeat
	while (next_index == cur_index) {
		next_index = random_num(quotes.length);
	}
	if (document) {	
		document.open();
		// create the quotes div
		document.write('<div id="quote"><h3>Art Quote for the Day:</h3><div class="float_right">');
		document.write('<input type="button" class="button" onclick="quoteSwitch();" value="see another" id="quote_change" />');
		document.write('</div><p>' + quotes[cur_index][0] + '<br /> - ' + quotes[cur_index][1] + '</p>');
		document.write("<br /></div>");
		document.close();
	}
}

// quoteSwitch()
// 1.  choose a new quote and fade it in
function quoteSwitch() {
	// get a new quote index that isn't one of the previous two--we'll use this below
	do {new_index = random_num(quotes.length);}
	while (new_index == cur_index || new_index == next_index);
	
	// extract text for new quote
	var txt = quotes[new_index][0] + '<br /> - ' + quotes[new_index][1];
	
	// get handles on <p>
	//var par = document.getElementById("quote");
	var $par = $('#quote p');
	// change to the new quote
	$par[0].innerHTML = txt;
}
